apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: namenode-tcp
  name: namenode-tcp
spec:
  ports:
    - name: "9870"
      port: 9870
      targetPort: 9870
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: namenode
  type: LoadBalancer
status:
  loadBalancer: {}
